import { User, NetworkNode, NetworkEdge, Recommendation } from '@/types';

// Demo users for testing without Firebase
export const demoUsers: User[] = [
  {
    id: 'demo-user-1',
    name: '김민수',
    email: 'minsu@example.com',
    company: 'TechStartup Inc.',
    position: 'CEO & Founder',
    bio: '기술로 세상을 바꾸는 꿈을 꾸고 있습니다',
    keywords: ['스타트업', 'AI', '투자', 'B2B', 'SaaS'],
    profileImage: undefined,
    inviteCode: 'NEX-001',
    invitesRemaining: 3,
    coffeeStatus: 'available',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-user-2',
    name: '이서연',
    email: 'seoyeon@example.com',
    company: 'DesignLab',
    position: 'Creative Director',
    bio: '디자인으로 브랜드의 가치를 높입니다',
    keywords: ['UX디자인', '브랜딩', '스타트업', '마케팅'],
    profileImage: undefined,
    inviteCode: 'NEX-002',
    invitesRemaining: 2,
    coffeeStatus: 'available',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-user-3',
    name: '박준영',
    email: 'junyoung@example.com',
    company: 'VentureCapital',
    position: 'Partner',
    bio: '혁신적인 스타트업을 발굴하고 성장시킵니다',
    keywords: ['투자', '스타트업', '핀테크', 'Web3'],
    profileImage: undefined,
    inviteCode: 'NEX-003',
    invitesRemaining: 5,
    coffeeStatus: 'busy',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-user-4',
    name: '최지은',
    email: 'jieun@example.com',
    company: 'MarketingPro',
    position: 'CMO',
    bio: '데이터 기반 마케팅 전략 전문가',
    keywords: ['마케팅', '그로스해킹', 'B2B', '콘텐츠'],
    profileImage: undefined,
    inviteCode: 'NEX-004',
    invitesRemaining: 3,
    coffeeStatus: 'available',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-user-5',
    name: '정현우',
    email: 'hyunwoo@example.com',
    company: 'CodeFactory',
    position: 'CTO',
    bio: '확장 가능한 아키텍처를 설계합니다',
    keywords: ['개발', 'AI', 'SaaS', '클라우드'],
    profileImage: undefined,
    inviteCode: 'NEX-005',
    invitesRemaining: 4,
    coffeeStatus: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-user-6',
    name: '강예진',
    email: 'yejin@example.com',
    company: 'HealthTech',
    position: 'Product Manager',
    bio: '헬스케어의 미래를 만들어갑니다',
    keywords: ['헬스케어', 'PM', '스타트업', 'B2B'],
    profileImage: undefined,
    inviteCode: 'NEX-006',
    invitesRemaining: 2,
    coffeeStatus: 'available',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-user-7',
    name: '윤성민',
    email: 'sungmin@example.com',
    company: 'EduNext',
    position: 'CEO',
    bio: '교육의 패러다임을 바꾸는 에듀테크',
    keywords: ['에듀테크', '스타트업', 'AI', '콘텐츠'],
    profileImage: undefined,
    inviteCode: 'NEX-007',
    invitesRemaining: 3,
    coffeeStatus: 'available',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Demo network graph
export const getDemoNetworkGraph = (userId: string): { nodes: NetworkNode[]; edges: NetworkEdge[] } => {
  const currentUser = demoUsers.find(u => u.id === userId) || demoUsers[0];

  const nodes: NetworkNode[] = [
    // Center node (current user)
    {
      id: currentUser.id,
      name: currentUser.name,
      profileImage: currentUser.profileImage,
      company: currentUser.company,
      position: currentUser.position,
      keywords: currentUser.keywords,
      degree: 0,
      connectionCount: 4,
    },
    // 1st degree connections
    {
      id: 'demo-user-2',
      name: '이서연',
      company: 'DesignLab',
      position: 'Creative Director',
      keywords: ['UX디자인', '브랜딩', '스타트업'],
      degree: 1,
      connectionCount: 3,
    },
    {
      id: 'demo-user-3',
      name: '박준영',
      company: 'VentureCapital',
      position: 'Partner',
      keywords: ['투자', '스타트업', '핀테크'],
      degree: 1,
      connectionCount: 5,
    },
    {
      id: 'demo-user-4',
      name: '최지은',
      company: 'MarketingPro',
      position: 'CMO',
      keywords: ['마케팅', '그로스해킹', 'B2B'],
      degree: 1,
      connectionCount: 4,
    },
    {
      id: 'demo-user-5',
      name: '정현우',
      company: 'CodeFactory',
      position: 'CTO',
      keywords: ['개발', 'AI', 'SaaS'],
      degree: 1,
      connectionCount: 3,
    },
    // 2nd degree connections
    {
      id: 'demo-user-6',
      name: '강예진',
      company: 'HealthTech',
      position: 'Product Manager',
      keywords: ['헬스케어', 'PM', '스타트업'],
      degree: 2,
      connectionCount: 2,
    },
    {
      id: 'demo-user-7',
      name: '윤성민',
      company: 'EduNext',
      position: 'CEO',
      keywords: ['에듀테크', '스타트업', 'AI'],
      degree: 2,
      connectionCount: 3,
    },
    {
      id: 'demo-user-8',
      name: '한수진',
      company: 'FinanceHub',
      position: 'CFO',
      keywords: ['핀테크', '투자', 'Web3'],
      degree: 2,
      connectionCount: 4,
    },
    {
      id: 'demo-user-9',
      name: '송태현',
      company: 'DataInsight',
      position: 'Data Scientist',
      keywords: ['AI', '데이터', 'SaaS'],
      degree: 2,
      connectionCount: 2,
    },
    {
      id: 'demo-user-10',
      name: '임지현',
      company: 'BrandStudio',
      position: 'Brand Manager',
      keywords: ['브랜딩', '마케팅', '콘텐츠'],
      degree: 2,
      connectionCount: 3,
    },
  ];

  const edges: NetworkEdge[] = [
    // 1st degree edges
    { source: currentUser.id, target: 'demo-user-2', degree: 1 },
    { source: currentUser.id, target: 'demo-user-3', degree: 1 },
    { source: currentUser.id, target: 'demo-user-4', degree: 1 },
    { source: currentUser.id, target: 'demo-user-5', degree: 1 },
    // 2nd degree edges
    { source: 'demo-user-2', target: 'demo-user-6', degree: 2 },
    { source: 'demo-user-2', target: 'demo-user-10', degree: 2 },
    { source: 'demo-user-3', target: 'demo-user-7', degree: 2 },
    { source: 'demo-user-3', target: 'demo-user-8', degree: 2 },
    { source: 'demo-user-4', target: 'demo-user-10', degree: 2 },
    { source: 'demo-user-5', target: 'demo-user-9', degree: 2 },
    { source: 'demo-user-5', target: 'demo-user-7', degree: 2 },
  ];

  return { nodes, edges };
};

// Demo recommendations
export const getDemoRecommendations = (userId: string): Recommendation[] => {
  return [
    {
      userId: 'demo-user-6',
      user: demoUsers[5],
      score: 0.85,
      keywordMatch: 0.6,
      proximityScore: 0.5,
      mutualConnections: 2,
      connectionPath: [userId, 'demo-user-2', 'demo-user-6'],
      reason: '김민수님과 관심사가 비슷합니다',
    },
    {
      userId: 'demo-user-7',
      user: demoUsers[6],
      score: 0.78,
      keywordMatch: 0.5,
      proximityScore: 0.5,
      mutualConnections: 3,
      connectionPath: [userId, 'demo-user-3', 'demo-user-7'],
      reason: '3명의 공통 인맥이 있습니다',
    },
    {
      userId: 'demo-user-9',
      user: {
        ...demoUsers[0],
        id: 'demo-user-9',
        name: '송태현',
        company: 'DataInsight',
        position: 'Data Scientist',
        keywords: ['AI', '데이터', 'SaaS'],
      },
      score: 0.72,
      keywordMatch: 0.7,
      proximityScore: 0.5,
      mutualConnections: 1,
      connectionPath: [userId, 'demo-user-5', 'demo-user-9'],
      reason: 'AI, SaaS에 관심이 있습니다',
    },
  ];
};

// Initial invite codes for demo
export const demoInviteCodes = [
  'ABC-123',
  'DEF-456',
  'GHI-789',
  'JKL-012',
  'MNO-345',
];
